export default [
  {
    linterOptions: {
      reportUnusedDisableDirectives: "off"
    },
    files: ["lib/**/*.js", "scripts/**/*.mjs", "scripts/**/*.js", "test/**/*.mjs", "test/**/*.js"],
    languageOptions: {
      ecmaVersion: 2024,
      sourceType: "module",
      globals: {
        globalThis: "readonly",
        console: "readonly",
        process: "readonly",
        Buffer: "readonly",
        setTimeout: "readonly",
        clearTimeout: "readonly",
        setInterval: "readonly",
        clearInterval: "readonly",
        setImmediate: "readonly",
        clearImmediate: "readonly",
        queueMicrotask: "readonly",
        structuredClone: "readonly",
        fetch: "readonly",
        Response: "readonly",
        Request: "readonly",
        Headers: "readonly",
        URL: "readonly",
        URLSearchParams: "readonly",
        AbortController: "readonly",
        AbortSignal: "readonly",
        TextDecoder: "readonly",
        TextEncoder: "readonly",
        crypto: "readonly",
        Map: "readonly",
        Set: "readonly",
        WeakMap: "readonly",
        WeakSet: "readonly",
        Promise: "readonly",
        Error: "readonly",
        TypeError: "readonly",
        RangeError: "readonly",
        ReferenceError: "readonly",
        SyntaxError: "readonly",
        Date: "readonly",
        Math: "readonly",
        JSON: "readonly",
        Number: "readonly",
        String: "readonly",
        Boolean: "readonly",
        Array: "readonly",
        Object: "readonly",
        RegExp: "readonly",
        Symbol: "readonly",
        BigInt: "readonly",
        Uint8Array: "readonly",
        ArrayBuffer: "readonly",
        DataView: "readonly",
      }
    },
    rules: {
      "no-undef": "error"
    }
  },
  {
    files: ["lib/client.js", "lib/client-parts/**/*.js", "lib/shim.js"],
    languageOptions: {
      globals: {
        window: "readonly",
        document: "readonly",
        navigator: "readonly",
        location: "readonly",
        history: "readonly",
        localStorage: "readonly",
        sessionStorage: "readonly",
        customElements: "readonly",
        HTMLElement: "readonly",
        Element: "readonly",
        Node: "readonly",
        Event: "readonly",
        CustomEvent: "readonly",
        MouseEvent: "readonly",
        MutationObserver: "readonly",
        requestAnimationFrame: "readonly",
        cancelAnimationFrame: "readonly",
        getComputedStyle: "readonly",
        alert: "readonly",
        confirm: "readonly",
        WebSocket: "readonly",
        FileReader: "readonly",
        Blob: "readonly",
        Image: "readonly",
        Notification: "readonly",
        performance: "readonly",
      }
    }
  }
];
